apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teamplan-cert
  namespace: teamplan
spec:
  secretName: teamplan-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - teamplan.thiemo.click
