---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: geoview
spec:
  encryptedData:
    .dockerconfigjson: AgC5FVKdj0Smexra+bXE/+7bjq5YC2OeVVkzgDwGKTcrTHWL/+6A4zp0VgwxXp2HqDfzQIXsMn+/3nz35K09UkM2P+K4VserBdXXF1VMWp4b0Mk15QJ+kgmpi71ZfonG75LesNehQ9q2HFj9aZY+b3OcDP4kO2qyhaveDDo6Fr9ad3dA+OaRksC6mvSWSpNY5HtTFyhJEeIHLWo4F2YhsZROUWeGOYulgck7AvBOywVUpgi+uWdSc5By3ySqpUpGHebKw7LcdMuKqHs0tCFpbhP/FAqG24JwDlcTHkZH1SRhjZMMkj1+ZXg5eymlpTOhPSb4kEpPYxo/r9ZE28PIMgM5F+R10JARmRvkWhDyIR1wpEu+jMJvD2/XOEb4KnMDiECogMvGsAgVVQnuIv76fQBa2Ein6ArFRhXSlpO5glgZtBbzCIvWpQTOOg/P/MMIL5vuF/NnVv/ikZ9fxVRKhU/PBqlAc9EqREjDXoMppkLK3Ln9A52lYP2YIecHdh40A4OACEJ/bIuh/mi48YFYprYkhjmoogPnyv8yFzAioWH2a+zBjnddQreKq3/5yGj6Hz5QW35PChMXpAVy181IUXbZ7tL0agpymPhoAb6dR7cIoBOhjKyHzi3G7TDxMkWcmapuaP7VMy6mYYPoqrchrtvLTDWDfbuzCpr8ThFFTb4/XvLh00Cpq8rba+bJZTc542GqIoxjRtjsC8TyZ3t2ROo5zfmM5EgRd1MFAeWAyJw4twAWqBjWg3ykydcx7SDfDXiIRcCxyzN5q0/LKeNiB4L4avySmOpvVugtm9gKwAm7Ds5QQ73l+l0OPyLJ7Dy9GzrtGm7Cj9Tp2e0nJesz9RasuyTfYUTP1nOBaX/Ah1tPoLV07qYX9PMZbjUTfUvsaeWA5SyME+wpywsOuiXhzA2uDgBnOUUoZdGiTgLu0wR553AJ1zmaE9etQQ==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: geoview
    type: kubernetes.io/dockerconfigjson
