---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kw-cert
  namespace: kw
spec:
  secretName: kw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - kw.thiemo.click
