---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: tandoor
spec:
  encryptedData:
    password: AgBMOWspb3OTbL8mQ9OftwclK8ndy33E3UJNwFn+P7G+8W3qa5YIGYPze6JrHxLxfrOUg+V4DcE03NWeaKaV4jmalaezkFYMEUiGhfdW4WbCVcE6ULnEx6pp+BeGC72/QfysMhLKkOMrwjQoYmJJZLhgPtXRaQjL+dX2xanG6f3Bj8km0TYYKtsJCMIwPV4qJSmnRKt6/0D5VPsPse3lqheeEukMNZUopA7cBJRqYodFWtl5S9hShqinacRLma+5sxIrSrfBm1YpIa6easvQ/atQMjyTNFq8BElYL9app57iIjvStIvTbEY1MBPFiKOg5KNIxvaPYOcfXpftFINL0ufoKvGdxWZ2L0mZSvq03LruDnpFFofPvzmFDly9mLxM0O568FslqlY27IATZjRoypSoSyk/bXaGeyB7X0mfQT96Ygb2oj2StaUy3ig6nncCswxyhUhqvgiallyWclu8/eetbeAShP8IGczYGOvWCrO00GL78pDyWp9cvSXlcWamMzqQYayf8Scnqmd8Fwki5kArSZq+IP5dvgAdX94a5QZlgkyfHG/uvPQ/Lg5fEjt0r03DDDiH70p3S/JvFDmirk2fvKy5m7WIQuRpCi/aIPImXRI18Ix2gbS+rhi38CYvCxrm4Ut7M1jp38A0jaOgeNgLbGClF+6eQvUEKlSfQXrmATPS23Zcc38VrQ1VQqm5svW/qhkyx8eexQ==
    username: AgBEeXHy+Qos4A7Yme+eIEeRDKUAsjFSOHfflhXK+kDkxYlLVtc+7EijAFq/n2AwbqRICIWP0MCK4UJ/F9cBumQtUB+OgR8jbWThIqtnGv2AAwcPV+ouqa6W67WemoybFGcfhfnjpTxcNOB2iXk+Y7NL4g75SGyInNKvODMKBbVFnU+8bB47BnNmrtX2PTwh1E8nSvJRqshZDCjeQDsuM/c5d+icHaCGn26dmAVbQ1h5QolTriWlSS4Xi4IwLFRClP4wkE2TpY4FHAz4olnSk/vtcgRoRu0g7AqWTiLRaE/q/6hyuxd7kbYkQwbfZuAzcm62JW2SMrlzNGX1C+iV+2tDQXDjpIGnY8nlFSDBgrJ6i8cv7XPe11+6cOO2gVtJhRPFLYfF5gtTKI0ikCih9GT7KDMwMbL7OFmYETvHfabatC95CKLNPwvk23HH7qUM/vV6/JBKezFXFBPqNYFE7RIdyxPnvHEe7sMLyk7ZOms8iJ9xGWQlDr0YoowyyEciU7NVXnQW6qOsDB+MT2UbZYf6fQeY8Av7J6s4Y0dwUL+GyM8ytUscwDBbgWjHmvGe8eLVCr5dG90qJiM71gDWuamFZKyDSaJOVPDSveRaN/pc0BuyQizHEMeMT/9k9lQNgwT2Rhx0prS2vcGC+OwCo8zu9mi/X2+T0YR5DOusKxG00TbrHrvBs9xs1E2PQAU0WsMFt8A/76ATNg==
  template:
    metadata:
      name: postgres-credentials
      namespace: tandoor
    type: Opaque
