---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tandoor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/thiemotorres/homelab.git
    targetRevision: HEAD
    path: apps/tandoor
  destination:
    server: https://kubernetes.default.svc
    namespace: tandoor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
