apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gork

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
  - gork-jwt-secret-sealed.yaml