---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: n8n
spec:
  encryptedData:
    password: AgBs53gAM0TFdbblpXXX/InbGLlrXDkMfR6DpHxwqtUpVD8B+JXhwJxq5c4P6q95TxkqYXt+IOFLHl9aZ288/Vix8D+zXZ+BggYDTAaEQqURsdFBBt4WInCpyJ5WeXlJh+hqDiwCdx4OL17u2kJ2/WGVJ2R7XNfS01KCiz/3IiHJUYdRZy3T8qqjYrO9waPBkHv+fUGT8iba0m8gM3r473nl/AtiZm2i4hK8Z8fAss4VKTwrFHcAepR6AJV5JScGhpoLRPiwrmJsbrXwv9nYJaNceOUje2csTfi7yq+vsz25h9q2FcIjmF6L1KX333Qdgc24qgbgPJiq4grHOe870vkaPIr/gE6zupOJQiOnBwbTkFQCPsNRZHdI0X3oeAA0Y6O1S+igrOtBrvXAcX4itqxgxp+Ih1x/i9J9GjReppS+u0JSjm/PuWjaK258mp6jxkWQI/YKz7Bb9Dtcd8jfdY94SJrMjKHpHtmswIaerEgX+TPbcl6hp9GyPP6yGjMsENcILBGSum4ekBDjWnWwOWFmoajCPl2lmVwUjbPThfhpl/g/GrCUdJCTjU2j+APK2WUV0Xi3uscd1WYMbfmgHdn+E4QkCMIcDZteheySBrQzBIhzZBuIo7+DhPqLKvqFOw3kZA4lOyvPgg1swM1V612DMDEISvF14O5WOAtgIGeV02bbAOKyw/bJ2VBO3R0aHhOZrIm+cBoFRA==
    username: AgCIfpu2gthCDQeYxjChBq57KyQmCSUHAWHxnkMXjadRWsJeQpjCjJk+alYNt3Rud9AJDiTZcA1LLLcbuSB2666ZsDTeQP2X0yA1oMmw5awrT51lsfvEwRbEJgOvx9ny1C+8x+ZaWKPO9JZI184saqgTQdxCJavMjZMo3wWuIQ3IU+mTrKaoTZvsOoj0Ol8MlC4Nh+IsMSxY1QSVUYIFEYx/8wE/F1arVHBm2/nixVHXPaWFxOriwN4wZZIGm/ypolInugjwcafNWJ2GJy3PhjXtHO8akrfwQpmv4QHD+LfJSA1df/ycXObww8/fUPyEzdXuQpJOfh2l5DhLQvKZdH1eFaXAxXaFbY2ggqWFBslYq+7bkosH21eMN3qc8h+gDcBX03HnkSidZFmze7IwKXwZu2/wdgYHB2C12C0C9CUVdwP84Rm0e/6x0A2g+MQJ8Ill+IrfPVtNV15NZ119DLt1lQSExP9eLm9yHKRdxMNCEWNHgR8UcvwxWjWBChSPIAEmcoJNMoEShIErEwQDp6eBiev609ef2kgiXRM4nA5BAoy8hscuJ5Ag/wdx4+xEYJ3DZQWBlNS2MZX9TCeC09deSt3kFyB0mM8kTo7UtmQP06q6oDE8Y1DXGLha5Yna0gsaaAOfYrHc8j5f7F3X1i6MvOOzf12MKLiX+Q4A5gDUfV+FdG444IlQbO2Ql5cVAZSClNRLrZGQAg==
  template:
    metadata:
      name: postgres-credentials
      namespace: n8n
