apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: navidrome-cert
  namespace: navidrome
spec:
  secretName: navidrome-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - navidrome.feto.dev
