apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-pvc
  namespace: navidrome
  labels:
    app: navidrome
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
