---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 32.2.0
    releaseName: traefik
    namespace: kube-system
    valuesFile: values.yaml
