traefik:
  ports:
    web:
      port: 80
      exposedPort: 80
    websecure:
      port: 443
      exposedPort: 443
      tls:
        enabled: true

  ingressRoute:
    dashboard:
      enabled: false  # Auf true setzen für Traefik Dashboard

  logs:
    general:
      level: INFO
    access:
      enabled: true

  additionalArguments:
    - "--api.dashboard=true"
    - "--ping=true"

  service:
    type: LoadBalancer  # Oder NodePort wenn kein MetalLB

  deployment:
    kind: DaemonSet  # Für K3s oft besser als Deployment
