apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hetzner-music-pvc
  namespace: navidrome
spec:
  storageClassName: hetzner-cifs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: hetzner-music-pv
