apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hetzner-n8n-pvc
  namespace: n8n
spec:
  storageClassName: hetzner-cifs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: hetzner-n8n-pv
