apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrowser-cert
  namespace: filebrowser
spec:
  secretName: filebrowser-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - files.feto.dev
