---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: gork
spec:
  encryptedData:
    password: AgCgBzVSfynOrOKnrwN7F+373QDP5YJS0SPt0BhBd3r8eCehbTGAmsk6//r7dTW5xo6GU1vSo+/LzyrPJJbSmPapgaTwC0rl09oVAYijTBD/0Usx28KM3L4XJO1jL2YQgB2xPeIZMDvb1ZmV+w1/VWr5nLGFRU4xxNBm91/roaYr/m5dn4aN4VLDtYq8MErqy2lbzrZeu3UGkdEEMNmM5oGa1BOQXhMc+7r89k/m1OBF24IPE6Zk8UKMXJ8oFLRl5zN7mbKtAm7oy7EpegOGoTTTI3R65zfgAkkdqOFVLUV0ZYasCe1E6MEuPXzSftznppQ4psfHKc/47YzmxwfyxwJrsWjyzS9RdZhtuaLin0lNF5zvMM0+uByYMO3OETYM2y6YRSG02tt7+l9hLupIjUoCVx4n4Mkp8SRNcbc6SDJ4oFhz7b3OMRCXfwDLDGBhpQ/1xaMDCwlpmId9WdMX6QYGJeiazCt76j29szt8pNF1DpJ0LomnQ6H8TlIourX5DCdo39lQ73IZxs6RLDAqbxHVdWPVvDS9G/j8VSTgxB4V0ValbbhNL0EHOib5YL5m02UWYip2H2EI8JOhwYMIwVb+Yhs566lSGePi55acmDORkW6oYhF1yXDdEZe7IY/0sKAqwOykXsLU9JXRnnpTgZc8NHCigYscyHn+lcN+AE8zeDvf05789DNuUUuxn4HY14OHwfa6aeyxIA==
    username: AgCKoQpIPSM2Boa8dq5kSoXbL3WcyFfd1yJr9BzmXDEnFnGr2KqHzKkrkShuN56eT+Y6iEJQSSq0dxtkmcVqtz51HXAUXHtx5uYjBOOznbjxQFmZ2B1RX7GYKy04i+GYaweFe0fXJQ7quM8lmqps2oDf4xqx89bBFh+/NiwHsF4LauklB9DlFRYtd2BgrYZsCp2DBa4PWn1ri8OEkV1QJqfdBbtCzAqnPfVbwWwgBwhImNhT2jw8VnR0MTaYmyfVGXI7erwP0xQ59GIdxpZ0xGBAvkzVtTM6KFTbqay5o87bfdoC4v//gw+wERrTHzpOiVir95hvqC85jSGDCgjDP/cMFtqouLinCU7SdHZ9+4obQwfKpKnbwE3VkRfLrCTY8U5lHm/girL2lO+pArumxoXbF7TAZBUu77PM+F0Aj0KVIWZuTz0+VKs/tifV6UiK5uQtI2hNnMRqeIvzJMP9MhSrwdl8XUIS400mGkW9tdCogygDlqQjy0mx8cR4elFE0BtbQXw1As0gyBRBpzgka8BbCXk6OWUXHkf3/zRwLhujJEOgKaIpZKyhmzxKPw5lrIdkSJj+MBoeEbBIloCO9McqwhV/HbzrZ3/GtvDURzn3jkoxiqlUcXhPa62Qf2gU19LIBPrvU229DQx1568WhTa8W75GCG2aODjvdnokX8ue7XbK12Q3ExxebR6pjd0ySrbKHF1KOiFpVQ==
  template:
    metadata:
      name: postgres-credentials
      namespace: gork
