---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: geoview-cert
  namespace: geoview
spec:
  secretName: geoview-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - geoview.thiemo.click
