---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: gork
spec:
  encryptedData:
    password: AgBZtuah42O8G/NzVshCebiJOOJZ1oOwgFUnjumVhBvMjlx3rE4t2MtLkRpMVnCY7PZB4rKE6v0A7QVqKKIvhDc6tL7raxZyp3UZte66Qa4an3qN8g8i2+vJKygsKHWHNynVvGNuLC/sMbcpArvXlW4RqVuE1IUx0L4/qIQvPu93bt8ZK4z7BVovonGU6pmljaVl0BfA2pMfntvDDVc0qlKCUE4rHbnYysvp+C8YXfdfnM4Ww4TYtajewWqUETuW9MzigW1GXU5Z9WWLeWW8VjpKFiBXGqBore3QGRAX9RexJ+cfE1sosX+WD7hwS53Va45ZwpLEdxhMOH7aUM9juaHINUychnh1RoUDgy2Bn9TE0cAzAF6tyKPipHdpmahK8p+7YjXT+RWZuYHheOw3YBMimNmp3UK2nq/vntFQQUsMf/otLvFrUGmPgZO3KbV0Osprcauk4QGxTMSXl7KLjbvW8Dk51etJbc/TmNaMmBFIyPIO4M/f0au/imy6oHUAujdx20NDflpsaRZ+MTWjhFH9IpHXAIw+zKNDqxqFvbix9gXZS9E1+CzdVSdz5WSaCFfgj5Z893r1rumPc6rrfiL3n9RmuIGfq0Nih0N9z4HarkokzRAZAIR1XQiah1U0gopKDhM0Qswmcj2Kb+JLg4MOIhM7JXZjhgDhjUGqG8Bckc9NjtQdXVgz1tun7q41sZaagNHyyHjCIQ==
    username: AgAOaRhI4w1/AyvQbSqnc4MRwUgM5XoG6ajR9Is+rTguFcJRGjRz9F6IW+vZBMdi/xnFuJhj5YEKYytxxHAP0++QqO8mwAHH/Wk0TEYj16VtiBkiBfGqJkvWZ8YVbXQczp+nOtJP2SPFEzGBk+tLGPLNiioYw4gxEmHcZg9RF5Eh/2989TW/zxXXLOgipYxW0ZioglSPitX3uTmeT1YW0m9NRC+Qo3SbWkzyK1AJeCcra6wQl+idMrxFAjr2JNoWXFbPjnOD0zBDq0wKvJuxQjCSKUV6TmKv/wcX4RRuoHY9zVDsHzCXZJe5CXBzZiAXetNhySsUhUhpMhzk0lCv0s+d/QXzhbYbFzAw2LAxvtz1BuBtQ5RmYpXfUc04BZAcfjbsrksZg8OXKpdkEnbnePS6flT9Eolbn/3mVKISA/nKi3lS0pTpUJJG9rmc0Vc7rjoufC8Vk1nihxvObare52VzJ4bVeQU7RhxCTcO/X3cbq3GmsrAyNhiRID1WI10lGn0WL3Qd8lKNJGqQmKWO4UPYGODBhyfV03wRIkpN63Io1AhpeQkIkHUI16GknRiKaQqCuDgNm1oqiwj7RgUyyJEQnjKPur4+N+Q83r1MGBOMstk6KnNNJOc+D3r4wJDCh5I6B7Cpv03gelI5Bv9fcJu6uVKDWwHe8QUa16zNG0Et9mGeA52bKyX9Jevf14WT/CowBfqFygHNPA==
  template:
    metadata:
      name: postgres-credentials
      namespace: gork
    type: Opaque
