---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBiC6V11dntCImUErh6nWBTkDZNDihTfujDg8ZfJHF/Aj7+QzCMv6XPKFk2ssRLKzPE6ze7KbdD2t9FzeH3qxoykrPp14tyUDeVHVz+WAISLpFkkDJUvC5Eytathy0y6M5Q5y0DpbACDbUubb50UT2SZL+1aWantaUrocAo46Q6tdKT+htwmzSzIk+kC/nWnrR22wOMF2Dsg5g64cQe6/xi4vjlVQWVbg7QlTjZJwewulzXrzc+7bsWVN2f2N/rXDThawUf5zde/W71Q68EKn0X9d10F5X9gYbxWpjFAu6V2O/CpCu7FIHrEwjB1AeRKbp5NtrR1D7tMge3+Oe00MuZwepXrWJSlg1se4xrCu+aVuZGEMfhQe238ENk8icOetdo8XpZ/24rWnxQYiPTgObaMFjePGPIclgcJIlHQAGMPvRyfFTXgG+AWKKlUUgwktP5aeMHRJyNUDlOzvtmGuYD16FEILL+qFsiIkloggTcrocrXFI2p6OQ+tbrL5B+W5G9ukhkZov13naNXYftnzk8B+8xa0vczEgv3K8jjLvmmbIP6zEQY9E/sC88BjR0zes32rDXn8OurxsjktFwFrVT+I7Vpb+slrjJvVP59TE28NynaI7DLBXng3eCzl6S85AC9/V72NcpTTUKzZ8N4xjF1kO+WasO0eiKcSPZJqdxky3RQzmBlNRdQ339JQfc5V0ZndDAkJ7yrCayPwkRyOZXaCNF+U/1tuLT1s9z6/k/k6hOPbFP+yB54VSUcA==
    admin-user: AgAGwfeW6i+VEysHc+8nhdhGFgLadrqiJfcz4yTX/SQG9Ezfd2hB2jAJVp8bCNUGMmxkH00wzbb9eeiXTDkG55I6NjkqxO7p2a99hKSWszY99jna6+A0L5i4APhczoMjPRozAp6kbbuGtj9r/8NLOLq9n4+iCcnd8g6LTqI4gkAAq9Ak0q1wSL+RCMH0ETbxMp7ZNSVDlt1peHzy8IES5JNsWQguV3k9330+DfLMlZVCN7CQB5zq0kEfv68EI7zI+gAxws3vqYMIFt4rlbOV9dMGE5z7N4qZaairz3tyCBjcAGsM8asjtPsowSo7dmMNNH3ZvreojooZagGzRv4UxeUuGoSL1QXlI4xO0JdsNr8ICT6ka5eoMKyy+YgQhndJeHnBP8we78R7IElWazwdsbLEGttEA/t4L+9gZrNYjJ+0RpbfxWkxBJ/0i67Blv7t0B+izIj9l198XrjWHY5mp75wU8uQ1zX9ybrWqVY79Svcw/vDDw74UDqUeKd7FquVvnsauAqZ4It2D2l1cZtfAn9ZPHliTgl6+6G/La0X1NPnSXhFOQJKgXDrt0Qsr1GavdXfv+087FF4CMCfV3wXwHNby59vBGtrgBu4c8ZyKkW5Qt3g+nBvpoakQx6tjKXnffTTe9yw0eL5rsOj/DgDnIS9PyIhwWtbHOfbjgtriYrDWZAJ0xoPQumZHH7sYMk35ZW3AkGnxw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
