---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - clusterissuer-staging.yaml
  - clusterissuer-prod.yaml
  - sealed-secrets/cloudflare-api-token-feto-sealed.yaml
  - sealed-secrets/cloudflare-api-token-thiemo-sealed.yaml
