---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-cert
  namespace: external-services
spec:
  secretName: home-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - home.feto.dev