---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: teamplan
spec:
  encryptedData:
    .dockerconfigjson: AgCIYcrQGlvk9GALeLhnxpp8PyuO8XzZX72cmNIJXeYsNTF1rp6CXQWIhIcTfvtdqF8Jg8BvXSOmmjP6SX0RhRk1exN0UwStFAlgyq6xFsON4tXWrvCJKo7gFgKLrIp3p0Fq2CxJTB/pAvkLlRL/zBt1l9tVMNIw9AEzMYZc0ygKtRGEDa38D1IaynrNjobFs9XUNR03svgPJsPvnMem6P1iIsx8fsGv7pEYj4EXGctfn9JYVIiTDQqAm8X42qAYoS+5ammBcQ7JYLGySuJbJ7Cia5th68pFB/5yM6krsO8Gttn9shtOd7Sq7YCaXw8hOzecmPkOXbfDPJ4nBqibiQVy3VfaJOXFXPJQQqubCJ47yH7CykpmhFtL7NmOnRM7eaU0iXn2RO4+8YAI6dnLeHaBLWb3OCMyiB3ORCFWj8DhOVz47N6gegGVETe6CROrgGknX4tKETTKTw/9fmXTRiPCCb9TMeZMjTAKJxsCRoiPVRnv/BhCq2V4EK6VQ4Qt87vwJ32zBkinYBJ7ye9+eLNb8BHj4/VBLeCNB6A1CtAkacDfO8wU8RgDNu86a4slE9S8KKj1KyKoKJvaJiLQMGH9Kr/PbWwrduSaFv1mmZroe14JVpVjTRSPinR7jr35bRVMb5FnWeZ4hsI7RsznxQErXDyDHvgOoXg707Gks6P98wkKSFf6IqdVztv6kce17sqQRypQTVAIADn0gnLSJqx7jNJr367F+vZjHiaY+0kSYY56B0qmjKntzVqlCZ4cSD7f4Suo1H3D4DuHbzofFbs7+cBOiv9uCjTyQlx7TNHgq/Y0rbxt42RAehWn243qeJmSXZ9FBlmGhV1pnIP1TZ033reyWijREVP9IoLGCFB1WMLvWW6tLgkmk5yvvlX401t38ZX3kw++teNosihrXPN0mO5yLFP/x8u5K5dr+7ViqGRg4rggTk554w==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: teamplan
    type: kubernetes.io/dockerconfigjson
